// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgsbGP7dyu549QOapEVKx6QDTs3yvjv0',
    appId: '1:914396685433:web:9a47a32dbcba218abc20a8',
    messagingSenderId: '914396685433',
    projectId: 'flashchat-6b0d5',
    authDomain: 'flashchat-6b0d5.firebaseapp.com',
    storageBucket: 'flashchat-6b0d5.appspot.com',
    measurementId: 'G-R0BR7LSKKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81MNEhz002skNn0pUEs_LMhygNraSJbU',
    appId: '1:914396685433:android:c3b2fc899a652870bc20a8',
    messagingSenderId: '914396685433',
    projectId: 'flashchat-6b0d5',
    storageBucket: 'flashchat-6b0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRuy7qGZH6Tm7UT8guOO2OODCW_1zFqJg',
    appId: '1:914396685433:ios:177f95a3dd97fd01bc20a8',
    messagingSenderId: '914396685433',
    projectId: 'flashchat-6b0d5',
    storageBucket: 'flashchat-6b0d5.appspot.com',
    iosClientId: '914396685433-dgq8pi0dhc59o9r390l5dknkgg0alqnk.apps.googleusercontent.com',
    iosBundleId: 'flashchat1.flashChat1',
  );
}
